#!/usr/bin/env python3
from pathlib import Path
import sys

if len(sys.argv) != 5:
    raise SystemExit("usage: build.py UPSTREAM CUSTOM EXTERNAL OUTPUT")

upstream = Path(sys.argv[1]).read_text(encoding="utf-8")
custom = Path(sys.argv[2]).read_text(encoding="utf-8").strip()
external = Path(sys.argv[3]).read_text(encoding="utf-8").strip()

marker = "[Rule]"
if marker not in upstream:
    raise SystemExit("Upstream config has no [Rule] section")

lines = [line for line in upstream.splitlines() if not line.strip().lower().startswith("update-url")]
upstream = "\n".join(lines) + "\n"
before, after = upstream.split(marker, 1)

header = (
    "# PERSONAL BUILD: minkaka/shadowrocket-rules\n"
    "# Base: Johnshall/Shadowrocket-ADBlock-Rules-Forever release/sr_cnip.conf\n"
    "# Generated automatically. Do not edit this file directly.\n\n"
)
output = (
    header + before + marker +
    "\n\n# ===== PERSONAL VERIFIED RULES (HIGHEST PRIORITY) =====\n" +
    custom +
    "\n# ===== END PERSONAL VERIFIED RULES =====\n" +
    "\n# ===== EXTERNAL SUPPLEMENTARY RULE SETS =====\n" +
    external +
    "\n# ===== END EXTERNAL SUPPLEMENTARY RULE SETS =====\n" +
    after
)
Path(sys.argv[4]).write_text(output, encoding="utf-8")
